# Generated by Django 3.0.3 on 2020-04-20 17:45

import urllib.request

from django.db import migrations

from ..ytchannel import YTChannel


def read_channel(apps, schema_editor):
    # Note we need to import the model from the historical version,
    # to work well if it is later changed
    Video = apps.get_model('youtube', 'Video')
    url = 'https://www.youtube.com/feeds/videos.xml?channel_id=' \
          + 'UC300utwSVAYOoRLEqmsprfg'
    xmlStream = urllib.request.urlopen(url)
    channel = YTChannel(xmlStream)
    for video in channel.videos():
        video = Video(id=video['id'], title=video['title'],
                      link=video['link'])
        video.save()

class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(read_channel)
    ]
